# Generated by Django 4.1.3 on 2022-11-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_balance_alter_user_balance_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionsHistory',
        ),
    ]
