# Generated by Django 4.1.3 on 2022-11-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_transactionshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
