# Generated by Django 4.1.3 on 2022-11-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
    ]
