# Generated by Django 4.1.3 on 2022-11-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_transactionshistory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionshistory',
            name='category',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
